.TH AWAKE 1 2024-02-26 2.0.1 ""
.SH NAME
\fBawake\fR \- Keep your Mac awake
.SH SYNOPSIS
\fBawake\fR [-d] [<duration> | <datetime>]
.SH DESCRIPTION
Keep your Mac awake, optionally for the specified duration (e\.g\. 12h30m) or until the specified datetime (e\.g\. 2030-01-01T00:00:00)\.
.SH OPTIONS
.TP
\fB\-d, \-\-daemon\fR
Run as daemon\.
.TP
\fB\-k, \-\-kill\fR
Kill any running awake processes\.
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
