.TH AWAKE 1 2024-02-24 1.1.0 ""
.SH NAME
\fBawake\fR \- Keep your Mac awake
.SH SYNOPSIS
\fBawake\fR [-d] [<duration>]
.SH DESCRIPTION
Keep your Mac awake, optionally for the specified duration (e\.g\. 3000s, 300m, 30h, 3d)\.
.SH OPTIONS
.TP
\fB\-d, \-\-daemonize\fR
Daemonize.
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
