# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "awake"
version = "1.0.0"
edition = "2021"
authors = ["Nick Dower <nicholasdower@gmail.com>"]

[dependencies]
core-foundation = "0.9.3"
libloading = "0.8.1"
signal-hook = "0.3.17"
