# See https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "awake"
version = "1.0.0"
edition = "2021"
authors = ["Nick Dower <nicholasdower@gmail.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
